joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

right_arm_controller:
  type: "joint_trajectory_controller/JointTrajectoryController"
  joints: ['leg_r1_joint','leg_r2_joint','leg_r3_joint','leg_r4_joint','leg_r5_joint','leg_r6_joint','leg_r7_joint']
  constraints:
    goal_time: 1.0
  state_publish_rate: 100
  action_monitor_rate: 50
