controller_list:
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - leg_r1_joint
      - leg_r2_joint
      - leg_r3_joint
      - leg_r4_joint
      - leg_r5_joint
      - leg_r6_joint
      - leg_r7_joint
initial:  # Define initial robot poses per group
#  - group: right_arm
#    pose: home

  []