controller_names:
  - arm_controller

arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - leg_r1_joint
    - leg_r2_joint
    - leg_r3_joint
    - leg_r4_joint
    - leg_r5_joint
    - leg_r6_joint
    - leg_r7_joint
