right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - leg_r1_joint
    - leg_r2_joint
    - leg_r3_joint
    - leg_r4_joint
    - leg_r5_joint
    - leg_r6_joint
    - leg_r7_joint
  gains:
    leg_r1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_r2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_r3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_r4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_r5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_r6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_r7_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1